// vue/src/components/CheckoutForm.vue
<script setup lang="ts">
import { ref } from "vue";
import { createSanwo } from "@sanwohq/web";
import { paystackProvider } from "@sanwohq/paystack";
import type { CheckoutResult } from "@sanwohq/types";

const email = ref("");
const amount = ref<number | undefined>();
const loading = ref(false);
const result = ref<{
  type: "success" | "cancelled" | "error";
  message: string;
} | null>(null);

// Initialize Sanwo with the Paystack provider and your public key
const sanwo = createSanwo({
  provider: paystackProvider,
  publicKey: "pk_test_xxxxxxxxxxxxxxxxxxxxx", // Replace with your Paystack public key
});

async function handlePayment() {
  if (!email.value || !amount.value) return;

  // Convert to kobo (minor units) for Paystack
  const amountInKobo = Math.round(amount.value * 100);

  loading.value = true;
  result.value = null;

  try {
    const response: CheckoutResult = await sanwo({
      amount: amountInKobo,
      currency: "NGN",
      customer: {
        email: email.value,
      },
    });

    if (response.status === "successful") {
      result.value = {
        type: "success",
        message: `Payment successful! Reference: ${response.reference}`,
      };
    } else if (response.status === "cancelled") {
      result.value = {
        type: "cancelled",
        message: "Payment was cancelled.",
      };
    } else if (response.status === "failed") {
      result.value = {
        type: "error",
        message: `Payment failed: ${response.error.message}`,
      };
    }
  } catch (error) {
    result.value = {
      type: "error",
      message: `Payment failed: ${error instanceof Error ? error.message : "Unknown error"}`,
    };
  } finally {
    loading.value = false;
  }
}
</script>

<template>
  <div class="container">
    <h1>Sanwo Payment</h1>
    <p class="subtitle">Vue 3 example with Paystack provider</p>

    <form @submit.prevent="handlePayment">
      <label for="email">Email</label>
      <input
        id="email"
        v-model="email"
        type="email"
        placeholder="customer@example.com"
        required
      />

      <label for="amount">Amount (NGN)</label>
      <input
        id="amount"
        v-model.number="amount"
        type="number"
        placeholder="1000"
        min="1"
        step="1"
        required
      />

      <button type="submit" :disabled="loading">
        {{ loading ? "Processing..." : "Pay Now" }}
      </button>
    </form>

    <div v-if="result" :class="['result', result.type]">
      {{ result.message }}
    </div>
  </div>
</template>

<style scoped>
.container {
  background: #fff;
  border-radius: 12px;
  box-shadow: 0 2px 16px rgba(0, 0, 0, 0.08);
  padding: 40px;
  width: 100%;
  max-width: 420px;
}

h1 {
  font-size: 1.5rem;
  margin-bottom: 8px;
}

.subtitle {
  color: #666;
  font-size: 0.9rem;
  margin-bottom: 24px;
}

label {
  display: block;
  font-size: 0.85rem;
  font-weight: 600;
  margin-bottom: 6px;
  color: #444;
}

input {
  width: 100%;
  padding: 10px 12px;
  border: 1px solid #ddd;
  border-radius: 8px;
  font-size: 1rem;
  margin-bottom: 16px;
  transition: border-color 0.2s;
}

input:focus {
  outline: none;
  border-color: #4f46e5;
}

button {
  width: 100%;
  padding: 12px;
  background: #4f46e5;
  color: #fff;
  border: none;
  border-radius: 8px;
  font-size: 1rem;
  font-weight: 600;
  cursor: pointer;
  transition: background 0.2s;
}

button:hover {
  background: #4338ca;
}

button:disabled {
  background: #a5b4fc;
  cursor: not-allowed;
}

.result {
  margin-top: 20px;
  padding: 14px;
  border-radius: 8px;
  font-size: 0.9rem;
}

.result.success {
  background: #ecfdf5;
  color: #065f46;
  border: 1px solid #a7f3d0;
}

.result.cancelled {
  background: #fffbeb;
  color: #92400e;
  border: 1px solid #fde68a;
}

.result.error {
  background: #fef2f2;
  color: #991b1b;
  border: 1px solid #fecaca;
}
</style>

// react/src/CheckoutForm.tsx
import { useState } from "react";
import { useSanwoCheckout } from "@sanwohq/react";
import type { CheckoutResult } from "@sanwohq/types";

export function CheckoutForm() {
  const { checkout, isLoading, error, result, reset } = useSanwoCheckout();

  const [email, setEmail] = useState("");
  const [amount, setAmount] = useState("");

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    const amountInKobo = Math.round(parseFloat(amount) * 100);

    try {
      await checkout({
        amount: amountInKobo,
        currency: "NGN",
        customer: { email },
        sanwoProviderOptions: {
          channels: ["card", "bank", "ussd", "bank_transfer"],
        },
      });
    } catch {
      // Error is captured in the hook's `error` state
    }
  };

  if (result) {
    return (
      <div style={styles.card}>
        <ResultDisplay result={result} />
        <button
          onClick={() => {
            reset();
            setEmail("");
            setAmount("");
          }}
          style={styles.secondaryButton}
        >
          Make another payment
        </button>
      </div>
    );
  }

  return (
    <div style={styles.card}>
      <h1 style={styles.title}>Sanwo + Paystack</h1>
      <p style={styles.subtitle}>React checkout example</p>

      <form onSubmit={handleSubmit} style={styles.form}>
        <div style={styles.field}>
          <label htmlFor="email" style={styles.label}>
            Email
          </label>
          <input
            id="email"
            type="email"
            required
            placeholder="customer@example.com"
            value={email}
            onChange={(e) => setEmail(e.target.value)}
            style={styles.input}
          />
        </div>

        <div style={styles.field}>
          <label htmlFor="amount" style={styles.label}>
            Amount (NGN)
          </label>
          <input
            id="amount"
            type="number"
            required
            min="1"
            step="0.01"
            placeholder="1000.00"
            value={amount}
            onChange={(e) => setAmount(e.target.value)}
            style={styles.input}
          />
        </div>

        <button
          type="submit"
          disabled={isLoading}
          style={{
            ...styles.button,
            opacity: isLoading ? 0.7 : 1,
            cursor: isLoading ? "not-allowed" : "pointer",
          }}
        >
          {isLoading ? "Processing..." : "Pay Now"}
        </button>
      </form>

      {error && (
        <div style={styles.errorBox}>
          <strong>Error:</strong> {error.message}
        </div>
      )}
    </div>
  );
}

function ResultDisplay({ result }: { result: CheckoutResult }) {
  switch (result.status) {
    case "successful":
      return (
        <div style={styles.successBox}>
          <h2 style={styles.resultTitle}>Payment Successful</h2>
          <p>Reference: {result.reference}</p>
          {result.transactionId && <p>Transaction ID: {result.transactionId}</p>}
        </div>
      );
    case "cancelled":
      return (
        <div style={styles.warningBox}>
          <h2 style={styles.resultTitle}>Payment Cancelled</h2>
          <p>The payment was cancelled by the user.</p>
        </div>
      );
    case "failed":
      return (
        <div style={styles.errorBox}>
          <h2 style={styles.resultTitle}>Payment Failed</h2>
          <p>{result.error.message}</p>
        </div>
      );
    case "pending":
      return (
        <div style={styles.warningBox}>
          <h2 style={styles.resultTitle}>Payment Pending</h2>
          <p>The payment is being processed.</p>
        </div>
      );
  }
}

const styles: Record<string, React.CSSProperties> = {
  card: {
    background: "#ffffff",
    borderRadius: 12,
    padding: 32,
    width: "100%",
    maxWidth: 420,
    boxShadow: "0 4px 24px rgba(0, 0, 0, 0.08)",
  },
  title: {
    fontSize: 24,
    fontWeight: 700,
    marginBottom: 4,
  },
  subtitle: {
    fontSize: 14,
    color: "#666",
    marginBottom: 24,
  },
  form: {
    display: "flex",
    flexDirection: "column",
    gap: 16,
  },
  field: {
    display: "flex",
    flexDirection: "column",
    gap: 4,
  },
  label: {
    fontSize: 13,
    fontWeight: 600,
    color: "#333",
  },
  input: {
    padding: "10px 12px",
    borderRadius: 8,
    border: "1px solid #ddd",
    fontSize: 15,
    outline: "none",
  },
  button: {
    marginTop: 8,
    padding: "12px 20px",
    borderRadius: 8,
    border: "none",
    background: "#0a7c42",
    color: "#fff",
    fontSize: 16,
    fontWeight: 600,
  },
  secondaryButton: {
    marginTop: 16,
    padding: "10px 20px",
    borderRadius: 8,
    border: "1px solid #ddd",
    background: "#fff",
    color: "#333",
    fontSize: 14,
    fontWeight: 500,
    cursor: "pointer",
    width: "100%",
  },
  errorBox: {
    marginTop: 16,
    padding: 12,
    borderRadius: 8,
    background: "#fef2f2",
    color: "#991b1b",
    fontSize: 14,
  },
  successBox: {
    padding: 16,
    borderRadius: 8,
    background: "#f0fdf4",
    color: "#166534",
    fontSize: 14,
  },
  warningBox: {
    padding: 16,
    borderRadius: 8,
    background: "#fffbeb",
    color: "#92400e",
    fontSize: 14,
  },
  resultTitle: {
    fontSize: 18,
    fontWeight: 700,
    marginBottom: 8,
  },
};
