// react-native/App.tsx
import React, { useState, useEffect } from "react";
import {
  SafeAreaView,
  ScrollView,
  View,
  Text,
  TextInput,
  TouchableOpacity,
  StyleSheet,
  Alert,
} from "react-native";
import {
  SanwoProvider,
  useSanwoCheckout,
  useSanwoContext,
} from "@sanwohq/react-native";
import type {
  SanwoProviderDefinition,
  CheckoutResult,
} from "@sanwohq/react-native";
import { paystackProvider } from "@sanwohq/paystack";
import { flutterwaveProvider } from "@sanwohq/flutterwave";
import { razorpayProvider } from "@sanwohq/razorpay";
import { monnifyProvider } from "@sanwohq/monnify";
import { interswitchProvider } from "@sanwohq/interswitch";

// ---------------------------------------------------------------------------
// Provider configurations
// ---------------------------------------------------------------------------

interface ProviderConfig {
  id: string;
  label: string;
  provider: SanwoProviderDefinition;
  publicKey: string;
  currency: string;
  sanwoProviderOptions: Record<string, unknown>;
}

const PROVIDERS: ProviderConfig[] = [
  {
    id: "paystack",
    label: "Paystack",
    provider: paystackProvider,
    publicKey: "pk_test_your_paystack_key",
    currency: "NGN",
    sanwoProviderOptions: {},
  },
  {
    id: "flutterwave",
    label: "Flutterwave",
    provider: flutterwaveProvider,
    publicKey: "FLWPUBK_TEST-your_flutterwave_key",
    currency: "NGN",
    sanwoProviderOptions: {},
  },
  {
    id: "razorpay",
    label: "Razorpay",
    provider: razorpayProvider,
    publicKey: "rzp_test_your_razorpay_key",
    currency: "INR",
    sanwoProviderOptions: {},
  },
  {
    id: "monnify",
    label: "Monnify",
    provider: monnifyProvider,
    publicKey: "MK_TEST_your_monnify_key",
    currency: "NGN",
    sanwoProviderOptions: { contractCode: "YOUR_CONTRACT_CODE", isTestMode: true },
  },
  {
    id: "interswitch",
    label: "Interswitch",
    provider: interswitchProvider,
    publicKey: "YOUR_MERCHANT_CODE",
    currency: "NGN",
    sanwoProviderOptions: { payItemId: "YOUR_PAY_ITEM_ID" },
  },
];

// ---------------------------------------------------------------------------
// Checkout form (must be rendered inside <SanwoProvider>)
// ---------------------------------------------------------------------------

function CheckoutForm({ config }: { config: ProviderConfig }) {
  const { checkout, isLoading, error, result, reset } = useSanwoCheckout();
  const { on } = useSanwoContext();

  const [email, setEmail] = useState("customer@example.com");
  const [amount, setAmount] = useState("5000");

  // Listen for success events via the event emitter
  useEffect(() => {
    const unsubscribe = on("success", (event) => {
      console.log("Payment succeeded:", event.data);
    });
    return unsubscribe;
  }, [on]);

  const handlePay = async () => {
    const numericAmount = parseFloat(amount);
    if (!email || isNaN(numericAmount) || numericAmount <= 0) {
      Alert.alert("Validation", "Please enter a valid email and amount.");
      return;
    }

    try {
      await checkout({
        amount: Math.round(numericAmount * 100), // convert to minor units
        currency: config.currency,
        customer: { email },
        description: "Sanwo React Native example payment",
        onLoad: () => console.log("Checkout loaded"),
        onError: (err) => console.log("Checkout error:", err),
        sanwoProviderOptions: config.sanwoProviderOptions,
      });
    } catch {
      // Error is captured in the hook's `error` state
    }
  };

  // ── Result screen ──
  if (result) {
    return (
      <View style={styles.section}>
        <ResultDisplay result={result} />
        <TouchableOpacity
          style={styles.secondaryButton}
          onPress={() => {
            reset();
            setAmount("5000");
          }}
        >
          <Text style={styles.secondaryButtonText}>Make another payment</Text>
        </TouchableOpacity>
      </View>
    );
  }

  // ── Form screen ──
  return (
    <View style={styles.section}>
      <Text style={styles.label}>Email</Text>
      <TextInput
        style={styles.input}
        value={email}
        onChangeText={setEmail}
        placeholder="customer@example.com"
        keyboardType="email-address"
        autoCapitalize="none"
      />

      <Text style={styles.label}>Amount ({config.currency})</Text>
      <TextInput
        style={styles.input}
        value={amount}
        onChangeText={setAmount}
        placeholder="5000"
        keyboardType="numeric"
      />

      <TouchableOpacity
        style={[styles.payButton, isLoading && styles.payButtonDisabled]}
        onPress={handlePay}
        disabled={isLoading}
      >
        <Text style={styles.payButtonText}>
          {isLoading ? "Processing..." : `Pay with ${config.label}`}
        </Text>
      </TouchableOpacity>

      {error && (
        <View style={styles.errorBox}>
          <Text style={styles.errorText}>Error: {error.message}</Text>
        </View>
      )}
    </View>
  );
}

// ---------------------------------------------------------------------------
// Result display
// ---------------------------------------------------------------------------

function ResultDisplay({ result }: { result: CheckoutResult }) {
  switch (result.status) {
    case "successful":
      return (
        <View style={styles.successBox}>
          <Text style={styles.resultTitle}>Payment Successful</Text>
          <Text>Reference: {result.reference}</Text>
          {result.transactionId && (
            <Text>Transaction ID: {result.transactionId}</Text>
          )}
        </View>
      );
    case "cancelled":
      return (
        <View style={styles.warningBox}>
          <Text style={styles.resultTitle}>Payment Cancelled</Text>
          <Text>The payment was cancelled by the user.</Text>
        </View>
      );
    case "failed":
      return (
        <View style={styles.errorBox}>
          <Text style={styles.resultTitle}>Payment Failed</Text>
          <Text style={styles.errorText}>{result.error.message}</Text>
        </View>
      );
    case "pending":
      return (
        <View style={styles.warningBox}>
          <Text style={styles.resultTitle}>Payment Pending</Text>
          <Text>The payment is being processed.</Text>
        </View>
      );
  }
}

// ---------------------------------------------------------------------------
// App root
// ---------------------------------------------------------------------------

export default function App() {
  const [selectedIndex, setSelectedIndex] = useState(0);
  const selected = PROVIDERS[selectedIndex];

  return (
    <SafeAreaView style={styles.container}>
      <ScrollView contentContainerStyle={styles.content}>
        <Text style={styles.title}>Sanwo Checkout</Text>
        <Text style={styles.subtitle}>React Native Example</Text>

        {/* Provider picker */}
        <Text style={styles.label}>Payment Provider</Text>
        <View style={styles.pickerRow}>
          {PROVIDERS.map((p, i) => (
            <TouchableOpacity
              key={p.id}
              style={[
                styles.pickerChip,
                i === selectedIndex && styles.pickerChipActive,
              ]}
              onPress={() => setSelectedIndex(i)}
            >
              <Text
                style={[
                  styles.pickerChipText,
                  i === selectedIndex && styles.pickerChipTextActive,
                ]}
              >
                {p.label}
              </Text>
            </TouchableOpacity>
          ))}
        </View>

        {/* Wrap the checkout form with SanwoProvider, keyed to re-mount on provider change */}
        <SanwoProvider
          key={selected.id}
          provider={selected.provider}
          publicKey={selected.publicKey}
        >
          <CheckoutForm config={selected} />
        </SanwoProvider>
      </ScrollView>
    </SafeAreaView>
  );
}

// ---------------------------------------------------------------------------
// Styles
// ---------------------------------------------------------------------------

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#f5f5f5",
  },
  content: {
    padding: 24,
    paddingTop: 48,
  },
  title: {
    fontSize: 28,
    fontWeight: "700",
    color: "#111",
  },
  subtitle: {
    fontSize: 14,
    color: "#666",
    marginBottom: 24,
  },
  section: {
    marginTop: 16,
  },
  label: {
    fontSize: 13,
    fontWeight: "600",
    color: "#333",
    marginBottom: 6,
    marginTop: 12,
  },
  input: {
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#ddd",
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 15,
    color: "#111",
  },
  pickerRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 8,
  },
  pickerChip: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#ddd",
    backgroundColor: "#fff",
  },
  pickerChipActive: {
    backgroundColor: "#0a7c42",
    borderColor: "#0a7c42",
  },
  pickerChipText: {
    fontSize: 13,
    color: "#333",
  },
  pickerChipTextActive: {
    color: "#fff",
    fontWeight: "600",
  },
  payButton: {
    marginTop: 20,
    backgroundColor: "#0a7c42",
    borderRadius: 8,
    paddingVertical: 14,
    alignItems: "center",
  },
  payButtonDisabled: {
    opacity: 0.6,
  },
  payButtonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "600",
  },
  secondaryButton: {
    marginTop: 16,
    borderWidth: 1,
    borderColor: "#ddd",
    borderRadius: 8,
    paddingVertical: 12,
    alignItems: "center",
    backgroundColor: "#fff",
  },
  secondaryButtonText: {
    color: "#333",
    fontSize: 14,
    fontWeight: "500",
  },
  errorBox: {
    marginTop: 16,
    padding: 12,
    borderRadius: 8,
    backgroundColor: "#fef2f2",
  },
  errorText: {
    color: "#991b1b",
    fontSize: 14,
  },
  successBox: {
    padding: 16,
    borderRadius: 8,
    backgroundColor: "#f0fdf4",
  },
  warningBox: {
    padding: 16,
    borderRadius: 8,
    backgroundColor: "#fffbeb",
  },
  resultTitle: {
    fontSize: 18,
    fontWeight: "700",
    marginBottom: 8,
  },
});

// angular/src/app/app.component.ts
import { Component, OnDestroy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { createSanwo, type SanwoInstance } from '@sanwohq/web';
import type {
  SanwoProviderDefinition,
  CheckoutResult,
} from '@sanwohq/types';
import { paystackProvider } from '@sanwohq/paystack';
import { flutterwaveProvider } from '@sanwohq/flutterwave';
import { razorpayProvider } from '@sanwohq/razorpay';
import { monnifyProvider } from '@sanwohq/monnify';
import { interswitchProvider } from '@sanwohq/interswitch';

export interface ScenarioConfig {
  id: string;
  label: string;
  description: string;
  group: string;
  provider: SanwoProviderDefinition;
  publicKey: string;
  currency: string;
  sanwoProviderOptions: Record<string, unknown>;
}

const SCENARIOS: ScenarioConfig[] = [
  // -- Paystack --
  {
    id: 'paystack-checkout',
    label: 'Paystack — Checkout',
    description: 'Standard Paystack checkout popup',
    group: 'Paystack',
    provider: paystackProvider,
    publicKey: 'pk_test_xxxxxxxxxxxx',
    currency: 'NGN',
    sanwoProviderOptions: { method: 'checkout' },
  },
  {
    id: 'paystack-new-transaction',
    label: 'Paystack — New Transaction',
    description: 'Paystack new transaction flow',
    group: 'Paystack',
    provider: paystackProvider,
    publicKey: 'pk_test_xxxxxxxxxxxx',
    currency: 'NGN',
    sanwoProviderOptions: { method: 'newTransaction' },
  },
  {
    id: 'paystack-card-only',
    label: 'Paystack — Card Only',
    description: 'Paystack checkout limited to card payments',
    group: 'Paystack',
    provider: paystackProvider,
    publicKey: 'pk_test_xxxxxxxxxxxx',
    currency: 'NGN',
    sanwoProviderOptions: { method: 'checkout', channels: ['card'] },
  },
  {
    id: 'paystack-bank-transfer',
    label: 'Paystack — Bank Transfer',
    description: 'Paystack checkout limited to bank transfer',
    group: 'Paystack',
    provider: paystackProvider,
    publicKey: 'pk_test_xxxxxxxxxxxx',
    currency: 'NGN',
    sanwoProviderOptions: { method: 'checkout', channels: ['bank_transfer'] },
  },

  // -- Flutterwave --
  {
    id: 'flutterwave-standard',
    label: 'Flutterwave — Standard',
    description: 'Standard Flutterwave checkout',
    group: 'Flutterwave',
    provider: flutterwaveProvider,
    publicKey: 'FLWPUBK_TEST-xxxxxxxxxxxx',
    currency: 'NGN',
    sanwoProviderOptions: {},
  },
  {
    id: 'flutterwave-card-only',
    label: 'Flutterwave — Card Only',
    description: 'Flutterwave checkout limited to card payments',
    group: 'Flutterwave',
    provider: flutterwaveProvider,
    publicKey: 'FLWPUBK_TEST-xxxxxxxxxxxx',
    currency: 'NGN',
    sanwoProviderOptions: { paymentOptions: 'card' },
  },

  // -- Razorpay --
  {
    id: 'razorpay-standard',
    label: 'Razorpay — Standard',
    description: 'Standard Razorpay checkout',
    group: 'Razorpay',
    provider: razorpayProvider,
    publicKey: 'rzp_test_xxxxxxxxxxxx',
    currency: 'INR',
    sanwoProviderOptions: {},
  },

  // -- Monnify --
  {
    id: 'monnify-standard',
    label: 'Monnify — Standard',
    description: 'Standard Monnify checkout',
    group: 'Monnify',
    provider: monnifyProvider,
    publicKey: 'MK_TEST_xxxxxxxxxxxx',
    currency: 'NGN',
    sanwoProviderOptions: {
      contractCode: 'xxxxxxxxxxxx',
      isTestMode: true,
    },
  },
  {
    id: 'monnify-card-only',
    label: 'Monnify — Card Only',
    description: 'Monnify checkout limited to card payments',
    group: 'Monnify',
    provider: monnifyProvider,
    publicKey: 'MK_TEST_xxxxxxxxxxxx',
    currency: 'NGN',
    sanwoProviderOptions: {
      contractCode: 'xxxxxxxxxxxx',
      isTestMode: true,
      paymentMethods: ['CARD'],
    },
  },
  {
    id: 'monnify-bank-transfer',
    label: 'Monnify — Bank Transfer Only',
    description: 'Monnify checkout limited to bank transfer',
    group: 'Monnify',
    provider: monnifyProvider,
    publicKey: 'MK_TEST_xxxxxxxxxxxx',
    currency: 'NGN',
    sanwoProviderOptions: {
      contractCode: 'xxxxxxxxxxxx',
      isTestMode: true,
      paymentMethods: ['ACCOUNT_TRANSFER'],
    },
  },

  // -- Interswitch --
  {
    id: 'interswitch-standard',
    label: 'Interswitch — Standard',
    description: 'Standard Interswitch checkout',
    group: 'Interswitch',
    provider: interswitchProvider,
    publicKey: 'xxxxxxxxxxxx',
    currency: 'NGN',
    sanwoProviderOptions: {
      payItemId: 'xxxxxxxxxxxx',
      siteRedirectUrl: typeof window !== 'undefined' ? window.location.href : '',
    },
  },
];

interface ScenarioGroup {
  group: string;
  items: ScenarioConfig[];
}

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [CommonModule, FormsModule],
  template: `
    <!-- Result View -->
    <div class="card" *ngIf="result">
      <div [ngSwitch]="result.status">
        <div *ngSwitchCase="'successful'" class="success-box">
          <h2 class="result-title">Payment Successful</h2>
          <p>Reference: {{ result.reference }}</p>
          <p *ngIf="asSuccessful(result)?.transactionId">
            Transaction ID: {{ asSuccessful(result)?.transactionId }}
          </p>
        </div>
        <div *ngSwitchCase="'cancelled'" class="warning-box">
          <h2 class="result-title">Payment Cancelled</h2>
          <p>The payment was cancelled by the user.</p>
        </div>
        <div *ngSwitchCase="'failed'" class="error-box">
          <h2 class="result-title">Payment Failed</h2>
          <p>{{ asFailed(result)?.error?.message }}</p>
        </div>
        <div *ngSwitchCase="'pending'" class="warning-box">
          <h2 class="result-title">Payment Pending</h2>
          <p>The payment is being processed.</p>
        </div>
      </div>
      <button class="secondary-button" (click)="resetResult()">
        Make another payment
      </button>
    </div>

    <!-- Checkout Form -->
    <div class="card" *ngIf="!result">
      <h1 class="title">Sanwo Checkout</h1>
      <p class="subtitle">Angular example &mdash; {{ selected.group }}</p>

      <form class="form" (ngSubmit)="handleSubmit()">
        <div class="field">
          <label for="scenario">Payment Scenario</label>
          <select
            id="scenario"
            class="select"
            [(ngModel)]="selectedId"
            name="scenario"
            (ngModelChange)="onScenarioChange($event)"
          >
            <optgroup *ngFor="let group of groups" [label]="group.group">
              <option *ngFor="let s of group.items" [value]="s.id">
                {{ s.label }}
              </option>
            </optgroup>
          </select>
          <span class="hint">{{ selected.description }}</span>
        </div>

        <div class="field">
          <label for="email">Email</label>
          <input
            id="email"
            type="email"
            required
            placeholder="customer@example.com"
            class="input"
            [(ngModel)]="email"
            name="email"
          />
        </div>

        <div class="field">
          <label for="amount">Amount ({{ selected.currency }})</label>
          <input
            id="amount"
            type="number"
            required
            min="1"
            step="0.01"
            placeholder="1000.00"
            class="input"
            [(ngModel)]="amount"
            name="amount"
          />
        </div>

        <button
          type="submit"
          class="button"
          [disabled]="isLoading"
        >
          {{ isLoading ? 'Processing...' : 'Pay with ' + selected.group }}
        </button>
      </form>

      <div class="error-box" *ngIf="error">
        <strong>Error:</strong> {{ error }}
      </div>
    </div>
  `,
})
export class AppComponent implements OnDestroy {
  scenarios = SCENARIOS;
  selectedId = SCENARIOS[0].id;
  selected: ScenarioConfig = SCENARIOS[0];
  groups: ScenarioGroup[] = [];

  email = '';
  amount = '';
  isLoading = false;
  error: string | null = null;
  result: CheckoutResult | null = null;

  private sanwoInstance: SanwoInstance | null = null;

  constructor() {
    this.groups = this.buildGroups();
    this.rebuildInstance();
  }

  ngOnDestroy(): void {
    if (this.sanwoInstance) {
      this.sanwoInstance.destroy();
    }
  }

  onScenarioChange(id: string): void {
    this.selected = this.scenarios.find((s) => s.id === id) ?? this.scenarios[0];
    this.error = null;
    this.rebuildInstance();
  }

  async handleSubmit(): Promise<void> {
    if (this.isLoading || !this.sanwoInstance) return;

    const numericAmount = parseFloat(this.amount);
    if (isNaN(numericAmount) || numericAmount <= 0) {
      this.error = 'Please enter a valid amount.';
      return;
    }

    const checkoutAmount = Math.round(numericAmount * 100);
    this.isLoading = true;
    this.error = null;

    try {
      this.result = await this.sanwoInstance({
        amount: checkoutAmount,
        currency: this.selected.currency,
        customer: { email: this.email },
        description: 'Sanwo example payment',
        onLoad: () => console.log('Sanwo: checkout loaded'),
        onError: (err) => console.log('Sanwo: checkout error', err),
        sanwoProviderOptions: this.selected.sanwoProviderOptions,
      });
    } catch (err) {
      this.error = err instanceof Error ? err.message : String(err);
    } finally {
      this.isLoading = false;
    }
  }

  resetResult(): void {
    this.result = null;
    this.email = '';
    this.amount = '';
  }

  asSuccessful(result: CheckoutResult | null) {
    return result?.status === 'successful' ? result : null;
  }

  asFailed(result: CheckoutResult | null) {
    return result?.status === 'failed' ? result : null;
  }

  private rebuildInstance(): void {
    if (this.sanwoInstance) {
      this.sanwoInstance.destroy();
    }
    this.sanwoInstance = createSanwo({
      provider: this.selected.provider,
      publicKey: this.selected.publicKey,
      containerId: 'sanwo-container',
    });
  }

  private buildGroups(): ScenarioGroup[] {
    const map = new Map<string, ScenarioConfig[]>();
    for (const s of this.scenarios) {
      const list = map.get(s.group) ?? [];
      list.push(s);
      map.set(s.group, list);
    }
    return Array.from(map.entries()).map(([group, items]) => ({
      group,
      items,
    }));
  }
}
